// MITMAGMPCOMLib.idl : IDL source for MITMAGMPCOMLib
//

// This file will be processed by the MIDL tool to
// produce the type library (MITMAGMPCOMLib.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(0a472b41-5eb4-4f00-a747-1640c22cc898),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IGetMITMAG : IDispatch
{
};
[
	uuid(0e915943-beb8-4e88-ac0b-8453d306dd72),
	version(1.0),
]
library MITMAGMPCOMLibLib
{
	importlib("stdole2.tlb");
	[
		uuid(60ee2daa-448e-4a9b-be95-62d509e17661)
	]
	coclass GetMITMAG
	{
		[default] interface IGetMITMAG;
	};
};

import "shobjidl.idl";
